### ISSUE TITLE
oracle downloads site changed?

### ISSUE THREAD

**Issue by ikzelf** [lucaslellis/oracle_quarter_patch_downloader#14]
tested with both python- v3.7 and v3.12 using the latest commit in master (3ac1315)

./oracle_quarter_patch_downloader.py --dry-run --debug -l
Initializing Downloader.
2023-12-07 10:31:20 - root - DEBUG - Starting Oracle Support logon
2023-12-07 10:31:20 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): updates.oracle.com:443
2023-12-07 10:31:21 - urllib3.connectionpool - DEBUG - https://updates.oracle.com:443 "GET /Orion/Services/download HTTP/1.1" 401 179
2023-12-07 10:31:21 - root - CRITICAL - Not able to connect to updates.oracle.com
Error message: Status code 401

I am pretty sure my credentials are correct and I can download https://updates.oracle.com/download/6880880.html without problems using a browser even with JavaScript disabled. I do see quite a few redirects before the form is presented.

The download button is connected to 
https://updates.oracle.com/Orion/Download/process_form/p6880880_230000_Linux-x86-64.zip?file_id=117550197&aru=25422636&userid=o-my-email&email=my-email;&patch_password=&patch_file=p6880880_230000_Linux-x86-64.zip

do you have any tip as how to debug and fix this?

**Comment by lucaslellis** [comment]
Hi Ronald,

I'll have to check it, it's been a while since I last used this script.

Kind Regards,

Lucas Pimentel Lellis

**Comment by ikzelf** [comment]
Hee, that automatically leads to the question: what are you using now for your automated downloads?

**Comment by lucaslellis** [comment]
Nothing, I haven't had to deal with large-scale patching for the last year
(and won't for the foreseeable future), but I'll keep this tool as a
learning experiment.

Kind Regards,

Lucas Pimentel Lellis

**Comment by ikzelf** [comment]
Guess what .... Just tested again and it looks like it's suddenly working again. No changes from my side.
