### ISSUE TITLE
How to download patches using proxy

### ISSUE THREAD

**Issue by ket000** [lucaslellis/oracle_quarter_patch_downloader#15]
How can I download the patches when behind proxy

**Comment by ket000** [comment]
Solved the issue.
export https_proxy=proxy.com:3128 (Replace proxy.com with the proxyserver name)
time ./oracle_quarter_patch_downloader.py --dry-run -f patch.csv -p aaa -u bbb
time ./oracle_quarter_patch_downloader.py -f patch.csv -p aaa -u bbb

**Comment by lucaslellis** [comment]
Hi,

Yes, that's correct, it uses the OS proxy configuration.

Kind Regards,

Lucas Pimentel Lellis

**Comment by lucaslellis** [comment]
Hi,

It uses the OS proxy configuration.

Kind Regards,
Lucas Lellis

**Comment by lucaslellis** [comment]
Hi,

Yes, that's correct, it uses the OS proxy configuration.

Kind Regards,

Lucas Pimentel Lellis
